In [2]:
import numpy as np
import torch

In [3]:
t = np.array([0, 1, 2, 3, 4, 5, 6])
print(t)

[0 1 2 3 4 5 6]


In [4]:
print("Rank : ", t.ndim)
print("Shape : ", t.shape)

Rank :  1
Shape :  (7,)


In [5]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
print(t.ndim)
print(t.shape)

2
(4, 3)


In [7]:
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.])


In [9]:
t = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [13]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1 * m2)
print(m1.mul(m2))
print(m1.matmul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[ 5.],
        [11.]])


In [14]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [15]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0)) # dim=0만 자리가 바뀌고, 나머지는 그대로인 상태로 평균
print(t.mean(dim=1)) # dim=1만 자리가 바뀌고 나머지로 평균
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [20]:
print(t.max())
print(t.max(dim=0)) # max 함수에 dim이 들어가면 두 개의 return값이 나온다. dim기준으로 max, dim기준으로 argmax
print(t.max(dim=0)[0])
print(t.max(dim=0)[1]) # argmax를 이런 식으로 표현한다. 조심!!

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])


In [22]:
t = np.array([[[ 0, 1, 2],
               [ 3, 4, 5]],

              [[ 6, 7, 8],
               [ 9,10,11]]])
ft = torch.FloatTensor(t)
print(t)
print(ft)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [25]:
# view : np의 reshape와 같은
print(t.reshape(-1, 3))
print(ft.view(-1, 3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [27]:
# squeeze : dimension중 단차원의 축을 없애줌.
ft = torch.FloatTensor([[0],[1],[2]])
ft.squeeze()

tensor([0., 1., 2.])

In [28]:
# unsqueeze : 원하는 dimension을 추가
ft = torch.FloatTensor([0, 1, 2])
print(ft.unsqueeze(0))
print(ft.unsqueeze(1))
print(ft.unsqueeze(-1))

tensor([[0., 1., 2.]])
tensor([[0.],
        [1.],
        [2.]])
tensor([[0.],
        [1.],
        [2.]])
