In [1]:
import numpy as np
import torch

In [2]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [3]:
lt.float()

tensor([1., 2., 3., 4.])

In [4]:
# ByteTensor : condition, T/F 사용 가능.
bt = torch.ByteTensor([True, False, False, True])
bt2 = (lt == 3)
print(bt)
print(bt2)

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([False, False,  True, False])


In [9]:
print(bt.bool())
print(bt2.byte())
print(bt.long())

tensor([ True, False, False,  True])
tensor([0, 0, 1, 0], dtype=torch.uint8)
tensor([1, 0, 0, 1])


In [10]:
# Concatenate
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim=0)) # dim = 0 방향으로 더해 준다
print(torch.cat([x, y], dim=1)) # dim = 1 방향으로 더해 준다

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [15]:
# stack : concat을 조금 더 편리하게 만들어준 것
x = torch.Tensor([1, 4])
y = torch.Tensor([2, 5])
z = torch.Tensor([3, 6])
# print(torch.cat([x, y, z], dim=1))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
