In [2]:
import numpy as np

In [3]:
# array generation, array shape

array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)

array2 = np.array([[1,2,3],
                   [4,5,6]])
print(type(array2))
print(array2.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)


In [4]:
# array dimension

print(array1.ndim)
print(array2.ndim)

1
2


In [5]:
# array data type

print(array1)
print(type(array1)) # array1 자체의 데이터 타입
print(array1.dtype) # array1의 요소의 데이터 타입

[1 2 3]
<class 'numpy.ndarray'>
int32


In [6]:
# array data type 변경하기

print(array1)
print(array1.dtype)
array_float = array1.astype('float64') # 결과값을 Return하는 메소드
print(array_float.dtype)

[1 2 3]
int32
float64


In [8]:
# ndarray 생성하기 : np.arange(), np.zeros, np.ones

sequence_array = np.arange(10) # [0:10]의 range로 된 ndarray 생성
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3, 2)) # 3, 2의 shape를 가진 0들로 이루어진 ndarray. 무조건 안에 tuple이 들어가야
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2)) # 3, 2 shape의 1로 이루어진 ndarray 마찬가지로 tuple
print(one_array)
print(one_array.dtype, one_array.shape)

arrayarray = np.ones_like(one_array)
print(arrayarray)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
# ndarray 차원 변경하는 reshape 메소드

print(sequence_array)
sequence_5_2_array = sequence_array.reshape(5,2)
print(sequence_5_2_array)

# (5, 2) 차원의 sequence array를 만들고 싶을 때는 그냥

temp_seq_array = np.arange(10).reshape(5,2)
print(temp_seq_array)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
# reshape 인자 중 하나에 -1 : 나머지 인자에 따라서 크기를 맞춰주게 함

seq_array = np.arange(24)
seq_array_reshaped = seq_array.reshape(4, 6)
seq_array_1 = seq_array.reshape(-1, 6) # 가로(열 개수)가 6이 되게끔
seq_array_2 = seq_array.reshape(4, -1) # 세로(행 개수)가 4가 되게끔

print(seq_array_1)
print(seq_array_2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [25]:
# tolist 메소드

print(seq_array.tolist())
print(seq_array_1.tolist())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]


In [34]:
# indexing... 매우 중요

# 1. 특정 데이터 추출
# 2. 슬라이싱
# 3. 팬시 인덱싱 . 인덱싱 집합을 리스트나 ndarray 형태로 지정
# 4. 불린 인덱싱

# 1. 단일 값 추출

array1 = np.arange(1, 11)
print(array1[2])
array2 = array1.reshape(2, 5)

try:
    print(array2[2])
except:
    print("Error")
    
print(array2[1, 4])

3
Error
10


In [39]:
# 2. slicing

array1 = np.arange(1, 10).reshape(3, -1)
print(array1)
print(array1[0:2, 2])

array2 = np.arange(1, 28).reshape(3, 3, -1)
print(array2)
print(array2[0:2, 1, 1:])

# 머릿속으로 그림 그려가면서 생각하기.
# slicing axis는 처음부터 0, 1, 2
# axis 0 : 제일 바깥쪽 괄호, 1 , 2, 이어질 수록 안쪽 괄호로

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[ 5  6]
 [14 15]]


In [41]:
# Fancy indexing

array1 = np.arange(1, 10).reshape(3, 3)
print(array1)
print(array1[[0,2],1:]) # axis 0 = 0, 2 두 개 (떨어진 행을 같이 쓰고싶을때)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [8 9]]


In [49]:
# Boolean indexing 매우 중요

array1 = np.arange(1, 10).reshape(3, 3)
print(array1>5)
print(array1[array1>5])

# array에 조건식을 붙이면 조건식을 지나고 True인 요소들의 자리에는 True, 그렇지 않으면 False를 리턴하는 array

print(array1[(array1>5)&(array1%2==0)]) # 5이상의 짝수

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[6 8]


In [61]:
# sort(), argsort()

#ndarray.sort() 하면 원래의 ndarray가 sort된 상태로 변환됨
#np.sort(ndarray) 하면 새로운 sorted ndarray를 반환, 그러므로 새로운 변수에 집어넣어줘야 함

#argsort() : sorted된 array의 순서를 다른 array에 적용시키고 싶을 때 사용.

name_array = np.array(['A','B','C','D','E'])
score_array = np.array([30, 50, 20, 90, 40])

sorted_idx = np.argsort(score_array)
print(score_array[sorted_idx]) # = score_array.sort() or np.sort(score_array)
print(name_array[sorted_idx])

# 내림차순으로 하고 싶다면.

reversed_idx = np.argsort(score_array)[::-1]
print(score_array[reversed_idx]) # = np.sort(score_array)[::-1]
print(name_array[reversed_idx])

print(np.sort(score_array)[::-1])

[20 30 40 50 90]
['C' 'A' 'E' 'B' 'D']
[90 50 40 30 20]
['D' 'B' 'E' 'A' 'C']
[90 50 40 30 20]


In [63]:
# 내적, Transpose

A = np.arange(6).reshape(2, 3)
B = np.array([3,4,2,5,6,6]).reshape(3,2)
print(np.dot(A, B))
print(A*B.reshape(2,3))  # reshape 메소드는 새로운 값을 반환함!
print(A.T) # np.transpose(A) 이거는 둘 다 새로운 값을 반환함.
print(B.T) # np.transpose(B)

[[14 17]
 [47 62]]
[[ 0  4  4]
 [15 24 30]]
[[0 3]
 [1 4]
 [2 5]]
[[3 2 6]
 [4 5 6]]


In [1]:
import numpy as np

In [8]:
arr = np.array([[2,1],
                [3,4]])

In [9]:
np.sort(arr, axis = 1)

array([[1, 2],
       [3, 4]])

In [11]:
arr[::-1]

array([[3, 4],
       [2, 1]])

In [12]:
np.zeros_like(arr)

array([[0, 0],
       [0, 0]])